# Generated by Django 5.2.5 on 2025-10-07 01:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0002_category_organization_zone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-date'], 'verbose_name': 'Alert', 'verbose_name_plural': 'Alerts'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['name'], 'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ['-date'], 'verbose_name': 'Measurement', 'verbose_name_plural': 'Measurements'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['name'], 'verbose_name': 'Zone', 'verbose_name_plural': 'Zones'},
        ),
        migrations.AddField(
            model_name='alert',
            name='is_resolved',
            field=models.BooleanField(default=False, help_text='Indica si la alerta ha sido resuelta'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de la alerta'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de borrado lógico', null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='device',
            field=models.ForeignKey(help_text='Dispositivo que generó la alerta', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='dispositivos.device'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='level',
            field=models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], db_index=True, default='MEDIUM', help_text='Nivel de criticidad de la alerta', max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='message',
            field=models.CharField(help_text='Mensaje descriptivo de la alerta', max_length=200),
        ),
        migrations.AlterField(
            model_name='alert',
            name='state',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', help_text='Estado del registro', max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de última actualización'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='category',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de borrado lógico', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, help_text='Nombre de la categoría', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='state',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', help_text='Estado del registro', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de última actualización'),
        ),
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.ForeignKey(help_text='Categoría del dispositivo', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='dispositivos.category'),
        ),
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='device',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de borrado lógico', null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='max_usage',
            field=models.PositiveIntegerField(help_text='Consumo máximo en watts', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(db_index=True, help_text='Nombre del dispositivo', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='organization',
            field=models.ForeignKey(help_text='Organización propietaria del dispositivo', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='dispositivos.organization'),
        ),
        migrations.AlterField(
            model_name='device',
            name='state',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', help_text='Estado del registro', max_length=10),
        ),
        migrations.AlterField(
            model_name='device',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de última actualización'),
        ),
        migrations.AlterField(
            model_name='device',
            name='zone',
            field=models.ForeignKey(help_text='Zona donde está ubicado el dispositivo', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='dispositivos.zone'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de la medición'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de borrado lógico', null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='device',
            field=models.ForeignKey(help_text='Dispositivo que generó la medición', on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='dispositivos.device'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='state',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', help_text='Estado del registro', max_length=10),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de última actualización'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='usage',
            field=models.FloatField(help_text='Consumo en KWh', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10000.0)]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de borrado lógico', null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(db_index=True, help_text='Email de contacto de la organización', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(db_index=True, help_text='Nombre de la organización', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='state',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', help_text='Estado del registro', max_length=10),
        ),
        migrations.AlterField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de última actualización'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de borrado lógico', null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(db_index=True, help_text='Nombre de la zona', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='state',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', help_text='Estado del registro', max_length=10),
        ),
        migrations.AlterField(
            model_name='zone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de última actualización'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('name', 'organization')},
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['device', '-date'], name='dispositivo_device__f56b01_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['level', '-date'], name='dispositivo_level_fee7ad_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['is_resolved', '-date'], name='dispositivo_is_reso_8f47df_idx'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['device', '-date'], name='dispositivo_device__5719a5_idx'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['-date'], name='dispositivo_date_a42396_idx'),
        ),
    ]
