# Generated by Django 5.2.5 on 2025-10-07 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0003_alter_alert_options_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', help_text='Estado del registro', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha de borrado lógico', null=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('OPERATOR', 'Operador'), ('VIEWER', 'Solo Lectura'), ('MANAGER', 'Gerente')], default='VIEWER', help_text='Rol del usuario en el sistema', max_length=50)),
                ('phone', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=20)),
                ('organization', models.ForeignKey(blank=True, help_text='Organización a la que pertenece el usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='dispositivos.organization')),
                ('user', models.OneToOneField(help_text='Usuario asociado al perfil', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'ordering': ['user__username'],
            },
        ),
    ]
